### ISSUE TITLE
Channel Prefix is appened twice (sometimes)

### ISSUE THREAD

**Issue by louispaulet** [FrDeamon/logger-extra-bundle#17]
Sometimes, DeamonLoggerExtraWebProcessor is called twice, resulting in a double prefix of the channel.
Here is the configuration :

- In config.yml:

```
monolog:
    channels: ['api', 'user', 'aws']
deamon_logger_extra:
    application:
        name: "%application_name%"
    handlers: [main_gelf, info_gelf]
    config:
        channel_prefix: "%application_version%"
```
- In config_dev:
```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        main_gelf:
            type: gelf
            publisher:
                hostname: "%graylog_host%"
            level: info
            channels: [!event]
        info_gelf:
            type:  gelf
            publisher:
                hostname: "%graylog_host%"
            level: info
            channels: [api, user, aws]
```
- In config_prod
```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        console:
            type:  console
        main_gelf:
            type:         fingers_crossed
            action_level: error
            handler:      nested_gelf
            channels: [!api, !user, !aws]
        nested_gelf:
            type:  gelf
            publisher:
                hostname: "%graylog_host%"
            level: info
        info_gelf:
            type:  gelf
            publisher:
                hostname: "%graylog_host%"
            level: info
            channels: [api, user, aws]
```
